---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-argo-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Test-Prep-AI/Config
    targetRevision: HEAD
    path: frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: frontend
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-argo-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Test-Prep-AI/Config
    targetRevision: HEAD
    path: backend
  destination:
    server: https://kubernetes.default.svc
    namespace: backend
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-argo-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Test-Prep-AI/Config
    targetRevision: HEAD
    path: model
  destination:
    server: https://kubernetes.default.svc
    namespace: model
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
