apiVersion: elbv2.k8s.aws/v1beta1
kind: IngressClassParams
metadata:
  name: alb-ingress-class-params
  namespace: kube-system # AWS Load Balancer Controller namespace
spec:
  scheme: internet-facing
  ipAddressType: ipv4
  tags:
    - key: Environment
      value: production
